[project]
name = "rag-groundx-mcp-server"
version = "0.1.0"
description = "MCP server for GroundX from eyelevel.ai, and local proxy for remote Google Drive MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
